# Generated by Django 4.2.3 on 2023-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='mytodo',
            name='diary',
        ),
    ]
