# Generated by Django 4.2.3 on 2023-07-12 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_rename_delete_mytodo_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
